mtp/urls.py
from django.contrib import admin
from django.conf.urls import  include,url
from django.urls import path
from django.contrib.auth import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mytrip.urls')),
    url(r'^accounts/login/$', views.login, name='login'),
    url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),
    path('social-auth/', include('social_django.urls', namespace="social")),
    path('accounts/', include('allauth.urls')),
    # path('', include('worldmap.urls')),

]

mytrip/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout, password_change as pwd_change, password_change_done as pwd_change_done, password_reset as reset, password_reset_done as reset_done, password_reset_confirm as reset_confirm, password_reset_complete as reset_complete
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from django.views.generic import TemplateView
from .views import weather, starter, getzomato, hotels,flights,location
from rest_framework.urlpatterns import format_suffix_patterns


app_name = 'mytrip'


urlpatterns = [
    path('', views.home, name='home'),
    # url(r'^$', views.home, name='home'),
    url(r'^home/$', views.home, name='home'),
    url(r'^register/$', views.register, name='register'),
    path('starter/', starter.as_view(), name='starter'),
    path('flights/', flights.as_view(), name='flights'),
    path('hotels/', hotels.as_view(), name='hotels'),
    path('weather/', weather.as_view(), name='weather'),
    path('location/', location.as_view(), name='location'),
    url(r'^getzomato/$', getzomato.as_view(), name='getzomato'),
    url('^password-change/done/$', pwd_change_done, name='password_change_done'),
    url('^password-change/$', pwd_change, {'post_change_redirect': '/password-change/done/'}, name='password_change'),
    url(r'^password-reset/complete/$', reset_complete, name='password_reset_complete'),
    url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', reset_confirm,
        {'post_reset_redirect': '/password-reset/complete/'}, name='password_reset_confirm'),
    url(r'^password-reset/done/$', reset_done, name='password_reset_done'),
    url(r'^password-reset/$', reset, {'post_reset_redirect': '/password-reset/done/',
                                      'email_template_name': 'registration/password_reset_email.html'},
        name='password_reset'),
    url(r'^userinterest_json/', views.UserInterestList.as_view()),
    ]

urlpatterns = format_suffix_patterns(urlpatterns)

mytrip/models.py
from django.db import models
from django.contrib.auth.models import User, Permission
from django import forms



class UserInterest (models.Model):
    user = models.CharField(max_length=500, null=False)
    origin = models.CharField(max_length=200, null=False)
    destination = models.CharField(max_length=200, null=False)
    searches = models.IntegerField(null=True)


    def __str__(self):
        return self.user + "  searched-> " + self.origin + "  to  "+ self.destination +  "-" + str(self.searches)

mytrip/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from .models import *
from .forms import LoginForm,UserRegistrationForm, CityForm, FlightsForm, ZomatoForm, Hotels, Location, SMS
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.views.generic import TemplateView
import requests
from django.conf import settings
from django.http import JsonResponse
from twilio.rest import Client
import twilio.rest

# now = timezone.now()
def home(request):
   return render(request, 'mytrip/home.html',
                 {'mytrip': home})

def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # Create a new user object but avoid saving it yet
            new_user = user_form.save(commit=False)
            # Set the chosen password
            new_user.set_password(
            user_form.cleaned_data['password'])
            # Save the User object
            new_user.save()
            return render(request, 'mytrip/register_done.html', {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request, 'mytrip/register.html', {'user_form': user_form})


class flights(TemplateView):
    template_name = 'mytrip/flights.html'


    def get(self, request):
        # if request.method == 'POST':
        #     radio = form.cleaned_data['one/two']
        #     if radio=='one':
        #         form = FlightsFormOne()
        #         return render(request, self.template_name, {'form': form})
        #     else:
                smsform = SMS()
                form = FlightsForm()
                return render(request, self.template_name, {'form': form},{'smsform':smsform})

    def post(self, request):
        data = {}
        # if request.method == 'POST':
        form = FlightsForm(request.POST)
        smsform = SMS(request.POST)
        flights_data = []
        if form.is_valid():
            input1 = form.cleaned_data['originplace']
            origin, orgcity = input1.split("-")
            # print(origin)
            # print(orgcity)
            input2 = form.cleaned_data['destinationplace']
            destination, destcity = input2.split("-")

            url = 'https://skyscanner-skyscanner-flight-search-v1.p.rapidapi.com/apiservices/browsequotes/v1.0/US/USD/en-US/'+ origin + '/' + destination + '/' + (form.cleaned_data['outboundpartialdate']).strftime("%Y-%m-%d")+ '/' + (form.cleaned_data['inboundpartialdate']).strftime("%Y-%m-%d")
            headers = {'X-RapidAPI-Key': settings.RAPIDAPI_API_KEY}
            api_response = requests.get(url, headers=headers)
            flights_json = api_response.json()
            if api_response.status_code == 200:
                form = FlightsForm()
                header= "Below are the Details for you Trip"
                for quote in flights_json['Quotes']:
                    # if quote['InboundLeg']['CarrierIds']== or  quote['OutboundLeg']['CarrierIds'] ==
                    airline_data={
                        'id':quote['QuoteId'],
                            'origin': origin,
                                'airportorigin': flights_json['Places'][1]['Name'],
                                'destination': destination,
                                'airportdest': flights_json['Places'][0]['Name'],
                                'startdate': quote['OutboundLeg']['DepartureDate'],
                                'returndate': quote['InboundLeg']['DepartureDate'],
                                'price': quote['MinPrice'],
                                'incarrier': quote['InboundLeg']['CarrierIds'],
                                'outcarrier': quote['OutboundLeg']['CarrierIds'],
                                 'carrier':flights_json['Carriers'],
                                'symbol': flights_json['Currencies'][0]['Symbol'],
                            }
                    flights_data.append(airline_data)
                th= 'th'
                context = {
                    'origin': origin,
                    'destination': destination,
                    'flights_data': flights_data,
                    'form': form,
                    'smsform':smsform,
                    'header': header,
                    'th':th,
                }

                return render(request, self.template_name, context)
            else:
                error = 'Please Check the Dates you entered'
                form = FlightsForm()
                context = {
                    'error' : error,
                    'form' : form,
                   }
                return render(request, self.template_name,context,)
        if smsform.is_valid():

            print(smsform.cleaned_data['body'])
            print(smsform.cleaned_data['phone'])
            account_sid = 'AC5b8851457d8da824d607170b838d4f7b'
            auth_token = 'd7afab61073fd9dd8b9a9e37c83eb961'
            client = Client(account_sid, auth_token)
            message = client.messages.create(
                body=smsform.cleaned_data['body'],
                from_='+15313018813',
                to=smsform.cleaned_data['phone'],
            )
            print(message)
            msg='msg'
            context = {
                'msg': msg,
                'message': 'SMS successful',
                'form': form,
                'smsform': smsform,
                'flights_data':flights_data,
            }
            return render(request, self.template_name, context, )

        else:
            msg = 'msg'
            error = 'Please Check the Details you entered'
            form = FlightsForm()
            context = {
                'msg': msg,
                'error' : error,
                'form' : form,
            }
            return render(request, self.template_name,context)



class starter(TemplateView):
    template_name = 'mytrip/starter.html'


    def get(self, request):
                form = FlightsForm()
                return render(request, self.template_name, {'form': form})



    def post(self, request):
        # if request.method == 'POST':
        form = FlightsForm(request.POST)
        if form.is_valid():
            input1 = form.cleaned_data['originplace']
            origin,orgcity = input1.split("-")
            # print(origin)
            # print(orgcity)
            input2 = form.cleaned_data['destinationplace']
            destination,destcity = input2.split("-")
            start = form.cleaned_data['outboundpartialdate'].strftime("%m/%d/%Y")
            end = form.cleaned_data['inboundpartialdate'].strftime("%m/%d/%Y")

            username = request.user.username
            if UserInterest.objects.filter(user=username).exists():
                if UserInterest.objects.filter(user=username).filter(origin=orgcity).filter(destination=destcity).exists():
                    object = UserInterest.objects.filter(user=username).get(origin=orgcity, destination=destcity)
                    object.searches = object.searches + 1
                    object.save()
                else:
                    entry = UserInterest(user=username, origin=orgcity, destination=destcity, searches=1)
                    entry.save()
            else:
                entry = UserInterest(user=username, origin=orgcity, destination=destcity, searches=1)
                entry.save()

            url = 'https://skyscanner-skyscanner-flight-search-v1.p.rapidapi.com/apiservices/browsequotes/v1.0/US/USD/en-US/'+ origin + '/' + destination+ '/' + (form.cleaned_data['outboundpartialdate']).strftime("%Y-%m-%d")+ '/' + (form.cleaned_data['inboundpartialdate']).strftime("%Y-%m-%d")
            headers = {'X-RapidAPI-Key': settings.RAPIDAPI_API_KEY}
            api_response = requests.get(url, headers=headers)
            flights_json = api_response.json()
            main_api = 'http://api.openweathermap.org/data/2.5/weather?q='
            api_key = '&units=metric&appid=907d8c401b542c8e7ede79a3ddea8f1a'
            map  = 'https://maps.googleapis.com/maps/api/directions/json?origin="'+orgcity+'"&destination="'+destcity+'"&key=AIzaSyDohjPYxETfcjKzjHoiqYGenuirmd0jWg0'
            url1 = main_api + orgcity + api_key
            url2 = main_api + destcity + api_key
            hotel = 'http://api.hotwire.com/v1/search/hotel?apiKey=eew8fwafckbky8563xfyw6te&format=json&startdate='+start+'&enddate='+end+'&dest='+destcity+'&children=1&adults=2&rooms=1&limit=5'
            org_data = requests.get(url1).json()
            dest_data = requests.get(url2).json()
            hotel_data = requests.get(hotel).json()
            # print(hotel_data)
            hotel_json=[]
            amn_json=[]
            place_json=[]

            map_json = []
            map_data = requests.get(map).json()
            map_values = {
                "start": map_data['routes'][0]['legs'][0]['start_address'],
                "end": map_data['routes'][0]['legs'][0]['end_address'],
                "distance": map_data['routes'][0]['legs'][0]['distance']['text'],
                "duration": map_data['routes'][0]['legs'][0]['duration']['text'],
            }
            map_json.append(map_values)
            if (api_response.status_code == 200) & (org_data['cod']==200) & (dest_data['cod']== 200) & (hotel_data['StatusCode'] == "0"):
                print("success")
                places= hotel_data["MetaData"]["HotelMetaData"]["Neighborhoods"]
                for place in hotel_data["MetaData"]["HotelMetaData"]["Neighborhoods"]:
                    hotel_area = {
                        "city": place['City'],
                        "state": place['State'],
                        "country": place['Country'],
                        "code": place['Id'],
                        "centroid": place['Centroid'],
                        "name": place['Name'],
                    }

mytrip/templates/mytrip/base.html
{% load staticfiles %}

<html lang="en">
<head>
    <title>MyTipPlanner</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="../../static/css/glyphicons.css">
    <link href="../../static/css/mytrip.css">
    <link href="../../static/css/font-awesome.css">
    <link href="../../static/css/font-awesome.min.css">
    <link href="../../static/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
            margin-bottom: 0;
            border-radius: 0;
            background-color: #282749;
        }
        /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
        .row.content {
            height: 500px
        }

        /* Set gray background color and 100% height */
        .sidenav {
            padding-top: 20px;
            background-color: #f1f1f1;
            height: 100%;
        }
        /* Set black background color, white text and some padding */
        footer {
            background-color: darkslateblue;
            color: white;
            padding: 15px;
        }
        /* On small screens, set height to 'auto' for sidenav and grid */
        @media screen and (max-width: 767px) {
            .sidenav {
                height: auto;
                padding: 15px;
            }
            .row.content {
                height: auto;
            }
        }
        .button {
  display: inline-block;
  border-radius: 4px;
  background-color: #0C0B4D;
  border: none;
  color: #FFFFFF;
  text-align: center;
  font-size: 28px;
  padding: 20px;
  width: 150px;
  transition: all 0.5s;
  cursor: pointer;
  margin: 5px;
}

.button span {
  cursor: pointer;
  display: inline-block;
  position: relative;
  transition: 0.5s;
}

.button span:after {
  content: '\00bb';
  position: absolute;
  opacity: 0;
  top: 0;
  right: -20px;
  transition: 0.5s;
}

.button:hover span {
  padding-right: 25px;
}

.button:hover span:after {
  opacity: 1;
  right: 0;
}

        .login-block{
    {#background: darkorchid;  /* fallback for old browsers */#}
{#background: -webkit-linear-gradient(to bottom,darkorchid, darkmagenta);  /* Chrome 10-25, Safari 5.1-6 */#}
{#background: linear-gradient(to bottom,darkorchid, darkmagenta); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */#}
float:left;
width:100%;
padding : 50px 0;
}
.banner-sec{background:url(https://static.pexels.com/photos/33972/pexels-photo.jpg)  no-repeat left bottom; background-size:cover; min-height:500px; border-radius: 0 10px 10px 0; padding:0;}
.container{background:#fff; background: rgba(255, 255, 255, 0.4); border-radius: 10px; box-shadow:15px 20px 0px rgba(0,0,0,0.1);}
.carousel-inner{border-radius:0 10px 10px 0;}
.carousel-caption{text-align:left; left:5%;}
.login-sec{padding: 50px 30px; position:relative;}
.login-sec .copy-text{position:absolute; width:80%; bottom:20px; font-size:13px; text-align:center;}
.login-sec .copy-text i{color: darkorchid;}
.login-sec .copy-text a{color:deeppink;}
.login-sec h2{margin-bottom:30px; font-weight:800; font-size:30px; color: #44426A;}
.login-sec h2:after{content:" "; width:100px; height:5px; background:#24BAD8; display:block; margin-top:20px; border-radius:3px; margin-left:auto;margin-right:auto}
.btn-login{background:#A28BCF; color:#3E2275; font-weight:600;}
.banner-text{width:70%; position:absolute; top:40px; padding-left:20px;}
.banner-text h2{color:#0C0B4D; font-weight:600;}
.banner-text h2:after{content:" "; width:100px; height:5px; background:#24BAD8; display:block; margin-top:20px; border-radius:3px;}
.banner-text h4{color:purple; font-weight:600;}
.banner-text p{color:#fff;}
        .box{
  background:#0C0B4D;
  width:400px;
  border-radius:3px;
  margin: 0 auto 0 auto;
  padding:0px 0px 70px 0px;
  border: azure 4px solid;
}

    </style>
</head>
<body id="app-layout" class="body" background="{% static 'images/background.jpg' %}" style="height: 100%;
  background-repeat: no-repeat;background-size: cover;background-attachment: fixed;">
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">

            <img src="{% static 'images/globe.png' %}" width="60" height="40" alt="logo">

            <a class="navbar-brand" href="{% url 'mytrip:home' %}" style="float: right; text-align: center">
                MyTripPlanner
            </a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar" style="float: right;">
            <ul class="nav navbar-nav">
                {% if user.is_authenticated %}
                <li><a href="{% url 'mytrip:home' %}">Home</a></li>
                    <li><a href="{% url 'mytrip:starter' %}">Plan</a></li>
                    <li><a href="{% url 'mytrip:location' %}">Location</a></li>
                    <li><a href="{% url 'mytrip:flights' %}">Flights</a></li>
                    <li><a href="{% url 'mytrip:hotels' %}">Hotels</a></li>
                <li><a href="{% url 'mytrip:weather' %}">weather</a></li>
                <li><a href="{% url 'mytrip:getzomato' %}">Food</a></li>
                {% endif %}
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                           More options <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'mytrip:password_change' %}"><i class="fa fa-btn fa-sign-out"></i>Change Password</a></li>
                            <li><a href="{% url 'logout' %}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                {% endif %}
            </ul>
        </div>

    </div>
</nav>

{#<div class="content container">#}
{#    <div class="row">#}
{#        <div class="col-md-12">#}
            {% block content %}
            {% endblock %}
{#            </div>#}
{#        </div>#}
{#</div>#}
</body>
</html>

mytrip/templates/mytrip/home.html
{% extends 'mytrip/base.html' %}
{% load staticfiles %}

<style>
.card {
  box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
  transition: 0.3s;
  width: 40%;
}

.card:hover {
  box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
}

.container {
  padding: 2px 16px;
}
</style>
{% block content %}

    <section class="login-block">
        <div class="container">
        <div class="row">

            <div class="col-md-12 login-sec">
        <h2 class="text-center">Welcome {{ user.username }}</h2>
            </div>
            {% if user.is_authenticated %}
 <div class="content container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="links">
                            <!-- Example row of columns -->
                                                            <div class="col-md-4">
                                    <div class="thumbnail">
                                        <div class="caption">
                                            <h3 style="font-family:Papyrus,fantasy; color: black;font-size: 38px" class="text-center"><strong>PLAN</strong></h3>
                                              <h3 style="font-family:Papyrus,fantasy; color: black;font-size: 20px" class="text-center">
                                                   The users can view entire trip plan in this plan page and get all related Information to plan your trip.</h3>
                                               <p><a class="btn" href="{% url 'mytrip:starter' %}"
                         role="button"><img class="d-block img-fluid" src="../../static/images/plan.gif" alt="First slide" width="100%" height="100%"></a></p>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="thumbnail">
                                        <div class="caption">
                                             <h3 style="font-family:Papyrus,fantasy; color: black;font-size: 38px" class="text-center"><strong>FOOD</strong></h3>
                                              <h3 style="font-family:Papyrus,fantasy; color: black;font-size: 20px" class="text-center">
                                                   Explore various food places at your destination.</h3>
                                        </div>
                                              <p><a class="btn" href="{% url 'mytrip:getzomato' %}"
                         role="button"><img class="d-block img-fluid" src="../../static/images/food.gif" alt="First slide" width="100%" height="80%"></a></p>
                                        </div>
                                    </div>

                                <div class="col-md-4">
                                    <div class="thumbnail">
                                        <div class="caption">
                                             <h3 style="font-family:Papyrus,fantasy; color: black;font-size: 38px" class="text-center"><strong>FLIGHTS</strong></h3>
                                              <h3 style="font-family:Papyrus,fantasy; color: black;font-size: 20px" class="text-center">
                                                   View various Flight deals.</h3>
                                        </div>
                                         <p><a class="btn" href="{% url 'mytrip:flights' %}"
                         role="button"><img class="d-block img-fluid" src="../../static/images/flight.gif" alt="First slide" width="85%" height="50%"></a></p>

                                    </div>
                                </div>

                                 <div class="col-md-4">
                                    <div class="thumbnail">
                                        <div class="caption">
                                              <h3 style="font-family:Papyrus,fantasy; color: black;font-size: 38px" class="text-center"><strong>DIRECTIONS</strong></h3>
                                              <h3 style="font-family:Papyrus,fantasy; color: black;font-size: 20px" class="text-center">
                                                   Get Driving directions</h3>
                                        </div>
                                         <p><a class="btn" href="{% url 'mytrip:location' %}"
                         role="button"><img class="d-block img-fluid" src="../../static/images/direction.gif" alt="First slide" width="100%" height="100%"></a></p>
                                    </div>
                                </div>
                            </div>
                             <div class="col-md-4">
                                    <div class="thumbnail">
                                        <div class="caption">
                                              <h3 style="font-family:Papyrus,fantasy; color: black;font-size: 38px" class="text-center"><strong>WEATHER</strong></h3>
                                              <h3 style="font-family:Papyrus,fantasy; color: black;font-size: 20px" class="text-center">
                                                   Check weather at different locations</h3>
                                        </div>
                                        <p><a class="btn" href="{% url 'mytrip:weather' %}"
                         role="button"><img class="d-block img-fluid" src="../../static/images/weather.gif" alt="First slide" width="100%" height="100%"></a></p>
                                    </div>
                                </div>
<div class="col-md-4">

                                    <div class="thumbnail">
                                        <div class="caption">
                                             <h3 style="font-family:Papyrus,fantasy; color: black;font-size: 38px" class="text-center"><strong>HOTELS</strong></h3>
                                              <h3 style="font-family:Papyrus,fantasy; color: black;font-size: 20px" class="text-center">
                                                   Check accomodation availability</h3>
                                        </div>
                                        <p><a class="btn" href="{% url 'mytrip:hotels' %}"
                         role="button"><img class="d-block img-fluid" src="../../static/images/hotel.gif" alt="First slide" width="100%" height="80%"></a></p

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            {% else %}
                    <div class="col-md-8">
                        <div class="links">
                           <h4 style="color: darkblue"> This apllication will allow users to collate and plan their trips.</h4>
                            <h4 style="color: darkblue"> Login to Experience our services</h4>
                        </div>
                    </div>
                     {% if ass.provider == 'instagram' %}
                        <div class="col-md-6 text-center">               <img src="{{ ass.extra_data.user.profile_picture }}" alt="" width="150" height="150" style="border-radius: 50%">             </div>
                        <div class="col-md-6 social-container my-2">
                        <p>Signed in via: {{ ass.provider }} </p>
                        <p> Name:  {{ ass.extra_data.user.full_name }} </p>
                        <p>Provider url: <a href="https://instagram.com/{{ ass.username }}">link</a></p>
                        {% endif %}


                    <div class="col-md-3">
                    <br>
                    <br>

                        <br>

 <button class="button"style="vertical-align:middle;"><a href="{% url 'login' %}"><span>Login </span></a></button>
                    </div>
                        </div>
{% endif %}



        </div>
        </div>

    </section>
{% endblock %}

mytrip/templates/mytrip/maps.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">


     <div class="container">
         <head>
    <title>Location Finder</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!--internet css files -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!--static css files -->
    <link rel="stylesheet" href="{% static 'css/animations.scss' %}">
    <link rel="stylesheet" href="{% static 'css/worldmap.css' %}">
    <link rel="stylesheet" href="{% static 'css/styling.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/media-queries.css' %}">

    <!--internet js files -->
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

   <!--APIs -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDcUbUzlOE1t6OIbdZpQx7k1IQgSfUYhmA&callback=initMap"
    async defer></script>

    <!--static js files -->
    <script type="text/javascript" src="{% static 'js/jquery.smoothscroll.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/js.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/worldmap.js' %}"></script>
    <script>
            $(function() {
            $('html').smoothScroll(500);
            });
    </script>

</head>
<body id="app-layout" onload="initMap()">

</div>
</body>
</html>

mytrip/templates/mytrip/register.html
<head>
    <link href="../../static/css/glyphicons.css">
    <link href="../../static/css/mytrip.css">
    <link href="../../static/css/font-awesome.css">
    <link href="../../static/css/font-awesome.min.css">
    <link href="../../static/css/bootstrap.min.css">
</head>
{% extends "mytrip/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    {% if form.errors %}
        <br xmlns:align-content="http://www.w3.org/1999/xhtml" xmlns:align-content="http://www.w3.org/1999/xhtml"/>
    <!--<p>Your username and password didn't match. Please try again.</p>-->
    {% endif %}

    <section class="login-block">
    <div class="container">
        <div class="row">
            <div class="col-md-4 login-sec">
		        <h2 class="text-center">Sign-up Here</h2>
                <form method="post" action="{% url 'mytrip:register' %}">
                    <div class="form-group">
                        {% csrf_token %}
                        {{ user_form|crispy  }}
                    </div>
                    <div class="form-check">
                        <button type="submit" class="btn btn-login">Create Account</button>
                    </div>
                </form>
            </div>
            	<div class="col-md-8 banner-sec">
 <div class="banner-text">
            <h2>Welcome to MyTripPlanner</h2>
                    <ul>
                        <li style="color: darkslateblue"><b>Plan</b></li>
                        <li style="color: darkslateblue"><b>Book</b></li>
                        <li style="color: darkslateblue"><b>Go</b></li>
                    </ul>
        </div>
                    <img class="d-block img-fluid" src="../../static/images/travel.gif" alt="First slide" width="100%" height="100%">


		</div>
                </div>
        </div>
</section>

{% endblock %}